### ISSUE TITLE
error: move to thiserror?

### ISSUE THREAD

**Issue by cyphar** [openSUSE/libpathrs#25]
This is basically a reboot of the `snafu` porting effort. I will need to consider this for a bit longer, but I like that `error-chain` has a much more opaque-to-the-user API -- all that's exposed is `ErrorKind`. Also the `foreign_links` feature composes much better than `snafu`. But I'll need to think about this a lot more (and probably create some test examples).

**Comment by HadrienG2** [comment]
Just in case you haven't seen this blog post pass by, here's [a nice overview/comparison](https://blog.yoshuawuyts.com/error-handling-survey/) of the various available Rust error handling crates.

**Comment by cyphar** [comment]
Based on my experience with https://github.com/cyphar/paperback, I suspect `thiserror` is going to be nicer. We will need to roll our own backtrace collection code though.

**Comment by cyphar** [comment]
Done in 500b5ff9157519639395de7384424b621ae8b7c3.
