### ISSUE TITLE
switch python bindings to pyo3

### ISSUE THREAD

**Issue by cyphar** [openSUSE/libpathrs#29]
Messing around with `cffi` is far too much of a pain (and also requires me to try to figure out `setuptools`). But pyo3 allows us to write Rust-native Python modules that don't have any other dependencies.

**Comment by DemiMarie** [comment]
This would be a regression for PyPy users.  PyPy’s implementation of CFFI is very heavily optimized, whereas the C API used by pyo3 must be emulated at a significant performance cost.

**Comment by cyphar** [comment]
We now use a proper build setup, so I suspect there is no longer any benefit to using pyo3 anyway.
