### ISSUE TITLE
switch to gha for ci

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/libpathrs#30]
JFYI: After the [re-occuring security problems with travis](https://arstechnica.com/information-technology/2022/06/credentials-for-thousands-of-open-source-projects-free-for-the-taking-again/) we disabled this CI provider for the openSUSE org. 

Not sure if this project is still alive.

**Comment by cyphar** [comment]
I've been busy with other things recently. I will migrate to GHA when I have some time next week.

**Comment by cyphar** [comment]
Done.
